import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  FileText, Plus, Download, Edit, Trash2, 
  Clock, User, GitBranch, Wand2
} from "lucide-react";

const MOCK_DOCS = [
  { 
    id: 1, 
    title: "API Reference", 
    projectId: 1,
    version: "1.0.0",
    isAutoGenerated: true,
    createdBy: "system",
    updatedAt: "2026-04-28T10:00:00Z"
  },
  { 
    id: 2, 
    title: "User Guide", 
    projectId: 1,
    version: "2.1.0",
    isAutoGenerated: false,
    createdBy: "user_1",
    updatedAt: "2026-04-27T15:00:00Z"
  },
  { 
    id: 3, 
    title: "Architecture Overview", 
    projectId: 1,
    version: "1.0.0",
    isAutoGenerated: true,
    createdBy: "system",
    updatedAt: "2026-04-26T09:00:00Z"
  },
];

export default function DocumentationPage() {
  const [selectedDoc, setSelectedDoc] = useState<number | null>(1);

  return (
    <div className="min-h-screen bg-[#0a0a0f] p-6">
      <div className="max-w-7xl mx-auto">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-3xl font-bold text-white">Documentation</h1>
            <p className="text-slate-400 mt-1">Auto-generated and manual documentation</p>
          </div>
          <div className="flex gap-3">
            <Button variant="outline" className="border-slate-700">
              <AutoFix className="w-4 h-4 mr-2" />
              Generate Docs
            </Button>
            <Button className="bg-cyan-500 hover:bg-cyan-600">
              <Plus className="w-4 h-4 mr-2" />
              New Document
            </Button>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Docs List */}
          <div className="lg:col-span-1">
            <Card className="bg-[#12121a] border-slate-800">
              <CardHeader>
                <CardTitle className="text-white">Documents</CardTitle>
              </CardHeader>
              <CardContent className="p-0">
                <div className="divide-y divide-slate-800">
                  {MOCK_DOCS.map((doc) => (
                    <div
                      key={doc.id}
                      className={`p-4 hover:bg-slate-800/50 cursor-pointer ${
                        selectedDoc === doc.id ? "bg-slate-800/50 border-l-2 border-cyan-500" : ""
                      }`}
                      onClick={() => setSelectedDoc(doc.id)}
                    >
                      <div className="flex items-start gap-3">
                        <FileText className="w-5 h-5 text-cyan-400 mt-0.5" />
                        <div className="flex-1">
                          <div className="text-white font-medium">{doc.title}</div>
                          <div className="flex items-center gap-2 mt-1">
                            <Badge variant="outline" className="border-slate-700 text-xs">
                              v{doc.version}
                            </Badge>
                            {doc.isAutoGenerated && (
                              <Badge className="bg-green-500/20 text-green-400 text-xs">
                                Auto
                              </Badge>
                            )}
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Doc Content */}
          <div className="lg:col-span-2">
            <Card className="bg-[#12121a] border-slate-800">
              <CardHeader className="flex flex-row items-center justify-between">
                <div>
                  <CardTitle className="text-white">
                    {MOCK_DOCS.find(d => d.id === selectedDoc)?.title}
                  </CardTitle>
                  <div className="flex items-center gap-2 mt-2">
                    <span className="text-slate-400 text-sm">
                      Version {MOCK_DOCS.find(d => d.id === selectedDoc)?.version}
                    </span>
                    <span className="text-slate-600">•</span>
                    <span className="text-slate-400 text-sm">
                      Updated {new Date(MOCK_DOCS.find(d => d.id === selectedDoc)?.updatedAt || "").toLocaleDateString()}
                    </span>
                  </div>
                </div>
                <div className="flex gap-2">
                  <Button variant="outline" className="border-slate-700">
                    <Download className="w-4 h-4 mr-2" />
                    Export
                  </Button>
                  <Button variant="outline" className="border-slate-700">
                    <Edit className="w-4 h-4 mr-2" />
                    Edit
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                <div className="prose prose-invert max-w-none">
                  <h2 className="text-white text-xl font-bold mb-4">Overview</h2>
                  <p className="text-slate-300 mb-6">
                    This documentation provides comprehensive information about the project APIs,
                    architecture, and usage guidelines.
                  </p>

                  <h2 className="text-white text-xl font-bold mb-4">API Endpoints</h2>
                  <div className="bg-slate-800 rounded-lg p-4 mb-6">
                    <code className="text-cyan-400">GET /api/users</code>
                    <p className="text-slate-400 text-sm mt-2">Retrieve all users</p>
                  </div>
                  <div className="bg-slate-800 rounded-lg p-4 mb-6">
                    <code className="text-cyan-400">POST /api/projects</code>
                    <p className="text-slate-400 text-sm mt-2">Create a new project</p>
                  </div>

                  <h2 className="text-white text-xl font-bold mb-4">Authentication</h2>
                  <p className="text-slate-300 mb-6">
                    All API requests require authentication via Bearer token in the Authorization header.
                  </p>

                  <h2 className="text-white text-xl font-bold mb-4">Error Handling</h2>
                  <p className="text-slate-300">
                    The API returns standard HTTP status codes. 4xx errors indicate client errors,
                    while 5xx errors indicate server errors.
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}