import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { 
  FileText, Plus, Download, Edit,
  Clock, Wand2, Database, Search, ShieldCheck,
  type LucideIcon,
} from "lucide-react";

const MOCK_DOCS = [
  { 
    id: 1, 
    title: "API Reference", 
    projectId: 1,
    version: "1.0.0",
    isAutoGenerated: true,
    createdBy: "system",
    updatedAt: "2026-04-28T10:00:00Z"
  },
  { 
    id: 2, 
    title: "User Guide", 
    projectId: 1,
    version: "2.1.0",
    isAutoGenerated: false,
    createdBy: "user_1",
    updatedAt: "2026-04-27T15:00:00Z"
  },
  { 
    id: 3, 
    title: "Architecture Overview", 
    projectId: 1,
    version: "1.0.0",
    isAutoGenerated: true,
    createdBy: "system",
    updatedAt: "2026-04-26T09:00:00Z"
  },
];

export default function DocumentationPage() {
  const [selectedDoc, setSelectedDoc] = useState<number | null>(1);

  return (
    <div className="min-h-screen bg-[#0a0a0f] p-6">
      <div className="max-w-7xl mx-auto">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-3xl font-bold text-white">Documentation</h1>
            <p className="text-slate-400 mt-1">Auto-generated and manual documentation</p>
          </div>
          <div className="flex gap-3">
            <Button variant="outline" className="border-slate-700">
              <Wand2 className="w-4 h-4 mr-2" />
              Generate Docs
            </Button>
            <Button className="bg-cyan-500 hover:bg-cyan-600">
              <Plus className="w-4 h-4 mr-2" />
              New Document
            </Button>
          </div>
        </div>

        <Card className="mb-6 border-emerald-500/20 bg-[#102019]">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-white">
              <Database className="h-5 w-5 text-emerald-300" />
              Private AI Database Intelligence
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="max-w-4xl text-sm leading-6 text-emerald-50/75">
              OCNE is designed for an AI teammate that understands a project's own database: current files, save snapshots, review threads, and project metadata. That gives teams project-specific answers without sending their proprietary patterns into a public training story.
            </p>
            <div className="mt-4 grid gap-3 md:grid-cols-4">
              {([
                ["Instant Project Familiarity", "Ask where API logic lives and how to use it on day one.", Search],
                ["AI-Powered Time Travel", "Find which save changed behavior by comparing Verlauf snapshots.", Clock],
                ["Context-Aware Intelligence", "Autocomplete can follow local naming, libraries, and conventions.", Wand2],
                ["Frictionless Documentation", "Generate clean save summaries and commit messages automatically.", FileText],
              ] satisfies Array<[string, string, LucideIcon]>).map(([title, text, Icon]) => (
                <div key={String(title)} className="rounded-lg border border-emerald-200/10 bg-black/20 p-3">
                  <Icon className="mb-2 h-4 w-4 text-emerald-300" />
                  <div className="text-xs font-semibold text-emerald-50">{title}</div>
                  <p className="mt-1 text-xs leading-5 text-emerald-50/65">{text}</p>
                </div>
              ))}
            </div>
            <div className="mt-4 rounded-lg border border-white/10 bg-black/20 p-3">
              <div className="flex items-center gap-2 text-sm font-semibold text-white">
                <ShieldCheck className="h-4 w-4 text-cyan-300" />
                Privacy promise
              </div>
              <p className="mt-2 text-xs leading-5 text-slate-300">
                Project intelligence is presented as project-scoped: the assistant learns from the selected workspace database and history, not from other teams' code, and not as public model training copy.
              </p>
            </div>
          </CardContent>
        </Card>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Docs List */}
          <div className="lg:col-span-1">
            <Card className="bg-[#12121a] border-slate-800">
              <CardHeader>
                <CardTitle className="text-white">Documents</CardTitle>
              </CardHeader>
              <CardContent className="p-0">
                <div className="divide-y divide-slate-800">
                  {MOCK_DOCS.map((doc) => (
                    <div
                      key={doc.id}
                      className={`p-4 hover:bg-slate-800/50 cursor-pointer ${
                        selectedDoc === doc.id ? "bg-slate-800/50 border-l-2 border-cyan-500" : ""
                      }`}
                      onClick={() => setSelectedDoc(doc.id)}
                    >
                      <div className="flex items-start gap-3">
                        <FileText className="w-5 h-5 text-cyan-400 mt-0.5" />
                        <div className="flex-1">
                          <div className="text-white font-medium">{doc.title}</div>
                          <div className="flex items-center gap-2 mt-1">
                            <Badge variant="outline" className="border-slate-700 text-xs">
                              v{doc.version}
                            </Badge>
                            {doc.isAutoGenerated && (
                              <Badge className="bg-green-500/20 text-green-400 text-xs">
                                Auto
                              </Badge>
                            )}
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Doc Content */}
          <div className="lg:col-span-2">
            <Card className="bg-[#12121a] border-slate-800">
              <CardHeader className="flex flex-row items-center justify-between">
                <div>
                  <CardTitle className="text-white">
                    {MOCK_DOCS.find(d => d.id === selectedDoc)?.title}
                  </CardTitle>
                  <div className="flex items-center gap-2 mt-2">
                    <span className="text-slate-400 text-sm">
                      Version {MOCK_DOCS.find(d => d.id === selectedDoc)?.version}
                    </span>
                    <span className="text-slate-600">•</span>
                    <span className="text-slate-400 text-sm">
                      Updated {new Date(MOCK_DOCS.find(d => d.id === selectedDoc)?.updatedAt || "").toLocaleDateString()}
                    </span>
                  </div>
                </div>
                <div className="flex gap-2">
                  <Button variant="outline" className="border-slate-700">
                    <Download className="w-4 h-4 mr-2" />
                    Export
                  </Button>
                  <Button variant="outline" className="border-slate-700">
                    <Edit className="w-4 h-4 mr-2" />
                    Edit
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                <div className="prose prose-invert max-w-none">
                  <h2 className="text-white text-xl font-bold mb-4">Overview</h2>
                  <p className="text-slate-300 mb-6">
                    This documentation provides comprehensive information about the project APIs,
                    architecture, and usage guidelines.
                  </p>

                  <h2 className="text-white text-xl font-bold mb-4">API Endpoints</h2>
                  <div className="bg-slate-800 rounded-lg p-4 mb-6">
                    <code className="text-cyan-400">GET /api/users</code>
                    <p className="text-slate-400 text-sm mt-2">Retrieve all users</p>
                  </div>
                  <div className="bg-slate-800 rounded-lg p-4 mb-6">
                    <code className="text-cyan-400">POST /api/projects</code>
                    <p className="text-slate-400 text-sm mt-2">Create a new project</p>
                  </div>

                  <h2 className="text-white text-xl font-bold mb-4">Authentication</h2>
                  <p className="text-slate-300 mb-6">
                    All API requests require authentication via Bearer token in the Authorization header.
                  </p>

                  <h2 className="text-white text-xl font-bold mb-4">Error Handling</h2>
                  <p className="text-slate-300">
                    The API returns standard HTTP status codes. 4xx errors indicate client errors,
                    while 5xx errors indicate server errors.
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
